### ISSUE TITLE
[bug][iOS] Landscape orientation recording 

### ISSUE THREAD

**Issue by mikron123** [Isvisoft/flutter_screen_recording#35]
when using landscape orientation, the phone is being recorded in a vertical resolution video, which causes the output to be "squashed" into it vertically.

**Comment by salime45** [comment]
I think this is fixed in the develop branch. Can you try?

**Comment by mikron123** [comment]
Did you do something new? because I tested the development branch a week ago

**Comment by salime45** [comment]
https://github.com/Isvisoft/flutter_screen_recording/commit/d5f7b6a97432451d28781067b42c5214dc40ee63

**Comment by mikron123** [comment]
It still happened in develop branch. But then I switched to master and it works! does it makes any sense?

**Comment by mikron123** [comment]
It works. now it doesn't ask me if to record with sound... so now I can record horizontally, but can't hear the mic :/

**Comment by mikron123** [comment]
Looks like this line is: var recordAudio: Bool = false;
false from the beginning?

**Comment by mikron123** [comment]
@salime45  is it working now?

**Comment by abdullah432** [comment]
I'm getting this issue at latest version `flutter_screen_recording: ^2.0.8`

**Comment by onstonboy** [comment]
I fixed the landscape recording for iOS. If anyone want can use my own repo. 

  flutter_screen_recording:
    git:
      url: https://github.com/onstonboy/flutter_screen_recording.git
      ref: 314c5fac5ada20a1085f27ea6f158f51d3f4b3da
      path: flutter_screen_recording

**Comment by onstonboy** [comment]
I fixed the landscape recording for iOS. If anyone want can use my own repo.

`
  flutter_screen_recording:
    git:
      url: https://github.com/onstonboy/flutter_screen_recording.git
      ref: 314c5fac5ada20a1085f27ea6f158f51d3f4b3da
      path: flutter_screen_recording`
